# .kodiak.toml
# Minimal config. version is the only required field.
version = 1
auto_approve_usernames = ["dependabot"]
merge.automerge_labels = ['dependencies','automerge ğŸš€']
update.autoupdate_labels = ['dependencies','autoupdate ğŸ”']
