# .kodiak.toml
# Minimal config. version is the only required field.
version = 1
auto_approve_usernames = ["dependabot"]
merge.automerge_label = 'automerge ğŸš€'
update.autoupdate_label = 'autoupdate ğŸ”'
